import { z } from 'zod'

export const restaurantSchema = z.object({
    name: z.string().min(2, 'Name must be at least 2 characters'),
    slug: z.string().min(2, 'Slug must be at least 2 characters'),
    logo: z.string().url().optional().or(z.literal('')),
    description: z.string().optional(),
    status: z.enum(['PENDING', 'ACTIVE', 'SUSPENDED']).default('PENDING'),
    subscription: z.enum(['FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE']).default('FREE'),
    facebookUrl: z.string().url().optional().or(z.literal('')),
    instagramUrl: z.string().url().optional().or(z.literal('')),
    tiktokUrl: z.string().url().optional().or(z.literal('')),
    metaPixelId: z.string().optional(),
    customDomain: z.string().optional().or(z.literal('')),
    contactName: z.string().optional(),
    contactPhone: z.string().optional(),
    contactEmail: z.string().email().optional().or(z.literal('')),
    notificationEmail: z.string().email().optional().or(z.literal('')),
    address: z.string().optional(),
    city: z.string().optional(),
    postCode: z.string().optional(),
    state: z.string().optional(),
    country: z.string().optional(),
    countryCode: z.string().optional(),
    cuisines: z.array(z.string()).optional(),
    serviceType: z.string().optional(),
    lat: z.number().optional(),
    lng: z.number().optional(),
    phone: z.string().optional(),
    subStartDate: z.string().optional().or(z.date()).optional(),
    subEndDate: z.string().optional().or(z.date()).optional(),
})
